name: wifi_device_manager
description: Application Flutter desktop pour la gestion, l’analyse et le contrôle des appareils WiFi.
version: 0.1.0

environment:
  sdk: '^3.9.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Gestion d'état
  flutter_riverpod: ^2.5.1
  
  # Réseau
  network_info_plus: ^5.0.3
  dart_ping: ^9.0.1
  lan_scanner: 4.0.0+1

  # Base de données locale
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Pour la gestion des chemins de fichiers (utile desktop)
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Qualité du code
  flutter_lints: ^4.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.8
  mockito: ^5.4.4

flutter:
  uses-material-design: true
  assets:
    - assets/